export function ScoreCard({ label, score, max = 10, color = 'blue' }) {
  const pct = score != null ? Math.round((score / max) * 100) : 0
  const colorMap = {
    blue: { bar: 'bg-blue-500', text: 'text-blue-600', bg: 'bg-blue-50' },
    green: { bar: 'bg-green-500', text: 'text-green-600', bg: 'bg-green-50' },
    orange: { bar: 'bg-orange-500', text: 'text-orange-600', bg: 'bg-orange-50' },
    purple: { bar: 'bg-purple-500', text: 'text-purple-600', bg: 'bg-purple-50' },
    red: { bar: 'bg-red-500', text: 'text-red-600', bg: 'bg-red-50' },
  }
  const c = colorMap[color] || colorMap.blue

  return (
    <div className="card p-4">
      <p className="text-sm text-gray-600 mb-2">{label}</p>
      <div className="flex items-center justify-between mb-2">
        <span className={`text-2xl font-bold ${c.text}`}>
          {score != null ? score.toFixed(1) : '—'}
        </span>
        <span className="text-xs text-gray-400">/ {max}</span>
      </div>
      <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-500 ${c.bar}`}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  )
}

export function ReadinessBadge({ level }) {
  const map = {
    'Interview Ready': { bg: 'bg-green-100', text: 'text-green-800', dot: 'bg-green-500' },
    'Strong': { bg: 'bg-blue-100', text: 'text-blue-800', dot: 'bg-blue-500' },
    'Good': { bg: 'bg-sky-100', text: 'text-sky-800', dot: 'bg-sky-500' },
    'Developing': { bg: 'bg-yellow-100', text: 'text-yellow-800', dot: 'bg-yellow-500' },
    'Needs Improvement': { bg: 'bg-red-100', text: 'text-red-800', dot: 'bg-red-500' },
  }
  const style = map[level] || map['Developing']
  return (
    <span className={`badge ${style.bg} ${style.text} gap-1.5`}>
      <span className={`w-1.5 h-1.5 rounded-full ${style.dot}`} />
      {level}
    </span>
  )
}

export function DemoNotice() {
  return (
    <div className="flex items-start gap-3 p-3 bg-amber-50 border border-amber-200 rounded-lg text-sm">
      <span className="text-amber-500 mt-0.5">⚠</span>
      <div>
        <p className="font-medium text-amber-800">Demo Mode — IBM Granite is not currently connected.</p>
        <p className="text-amber-700 text-xs mt-0.5">
          Set WATSONX_URL, WATSONX_API_KEY, and WATSONX_PROJECT_ID environment variables to enable real IBM Granite AI responses.
        </p>
      </div>
    </div>
  )
}

export function GraniteNotice() {
  return (
    <div className="flex items-start gap-3 p-3 bg-green-50 border border-green-200 rounded-lg text-sm">
      <span className="text-green-600 mt-0.5">✓</span>
      <p className="font-medium text-green-800">IBM Granite AI is active — responses are generated by IBM Granite via watsonx.ai.</p>
    </div>
  )
}

export function LoadingSpinner({ label = 'Loading...' }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 gap-3">
      <div className="w-8 h-8 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
      <p className="text-sm text-gray-500">{label}</p>
    </div>
  )
}

export function ErrorMessage({ message, onRetry }) {
  return (
    <div className="card p-6 text-center">
      <p className="text-red-500 font-medium mb-2">Something went wrong</p>
      <p className="text-sm text-gray-600 mb-4">{message}</p>
      {onRetry && (
        <button className="btn-secondary text-sm" onClick={onRetry}>
          Try Again
        </button>
      )}
    </div>
  )
}

export function ProgressBar({ current, total, label }) {
  const pct = total > 0 ? Math.round((current / total) * 100) : 0
  return (
    <div>
      {label && (
        <div className="flex justify-between text-xs text-gray-500 mb-1">
          <span>{label}</span>
          <span>{current} / {total}</span>
        </div>
      )}
      <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
        <div
          className="h-full bg-blue-500 rounded-full transition-all duration-300"
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  )
}
