import { useNavigate } from 'react-router-dom'
import { BrainCircuit, Zap, Target, FileSearch, BarChart2, CheckCircle2, ArrowRight } from 'lucide-react'

const features = [
  {
    icon: FileSearch,
    title: 'Resume-Powered Questions',
    desc: 'Upload your resume — the AI generates questions tailored to your specific projects, skills, and experience.',
  },
  {
    icon: BrainCircuit,
    title: 'IBM Granite AI Evaluation',
    desc: 'Every answer is evaluated by IBM Granite, providing scores, strengths, weaknesses, and model answers.',
  },
  {
    icon: Zap,
    title: 'Adaptive Follow-Up Questions',
    desc: 'The AI dynamically follows up on weak answers, simulating a real interviewer conversation.',
  },
  {
    icon: Target,
    title: 'RAG-Powered Knowledge',
    desc: 'Retrieval-Augmented Generation retrieves role-specific knowledge to generate highly relevant questions.',
  },
  {
    icon: BarChart2,
    title: 'Performance Analytics',
    desc: 'Track your progress across technical, HR, and behavioral dimensions with detailed score analytics.',
  },
  {
    icon: CheckCircle2,
    title: 'Personalised Study Plan',
    desc: 'Receive a day-by-day preparation plan targeting your specific weak areas after each interview.',
  },
]

const steps = [
  { step: '01', title: 'Set Up Your Profile', desc: 'Enter your target role, experience, and skills.' },
  { step: '02', title: 'Upload Your Resume', desc: 'IBM Granite analyses your resume to extract key information.' },
  { step: '03', title: 'Configure Your Interview', desc: 'Choose interview type, difficulty, and question count.' },
  { step: '04', title: 'RAG Retrieval', desc: 'The system retrieves relevant role-specific interview knowledge.' },
  { step: '05', title: 'Answer Questions', desc: 'Answer personalised questions generated by IBM Granite.' },
  { step: '06', title: 'Get Instant Feedback', desc: 'Receive detailed AI evaluation with improvement suggestions.' },
  { step: '07', title: 'Review Your Report', desc: 'See your overall score, readiness level, and weak areas.' },
  { step: '08', title: 'Follow Your Plan', desc: 'Use your personalised study plan to prepare for the real interview.' },
]

export default function Landing() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="border-b border-gray-100 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <BrainCircuit size={18} className="text-white" />
            </div>
            <span className="font-bold text-gray-900">AI Interview Trainer</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate('/dashboard')}
              className="text-sm font-medium text-gray-600 hover:text-gray-900"
            >
              Dashboard
            </button>
            <button
              onClick={() => navigate('/interview/setup')}
              className="btn-primary text-sm"
            >
              Start Interview
            </button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-6xl mx-auto px-6 py-20 text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-blue-50 border border-blue-200 rounded-full text-xs font-medium text-blue-700 mb-6">
          <BrainCircuit size={13} />
          Powered by IBM Granite · Problem Statement No. 22
        </div>
        <h1 className="text-5xl font-bold text-gray-900 mb-5 leading-tight">
          AI Interview Trainer
        </h1>
        <p className="text-xl text-gray-500 mb-10 max-w-2xl mx-auto leading-relaxed">
          Practice smarter. Answer better. Get interview-ready with AI.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <button
            onClick={() => navigate('/interview/setup')}
            className="btn-primary flex items-center justify-center gap-2 text-base px-8 py-3"
          >
            Start Interview <ArrowRight size={18} />
          </button>
          <button
            onClick={() => navigate('/dashboard')}
            className="btn-secondary text-base px-8 py-3"
          >
            Go to Dashboard
          </button>
        </div>
      </section>

      {/* How it works */}
      <section className="bg-gray-50 py-16">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-2">How It Works</h2>
          <p className="text-center text-gray-500 text-sm mb-10">
            End-to-end interview preparation in 8 steps
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {steps.map((s) => (
              <div key={s.step} className="card p-4">
                <div className="text-2xl font-bold text-blue-100 mb-2">{s.step}</div>
                <h3 className="font-semibold text-gray-900 text-sm mb-1">{s.title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-6xl mx-auto px-6 py-16">
        <h2 className="text-2xl font-bold text-gray-900 text-center mb-2">Key Features</h2>
        <p className="text-center text-gray-500 text-sm mb-10">
          Comprehensive preparation for technical, HR, and behavioral interviews
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {features.map((f) => (
            <div key={f.title} className="card p-5">
              <div className="w-10 h-10 bg-blue-50 rounded-lg flex items-center justify-center mb-4">
                <f.icon size={20} className="text-blue-600" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">{f.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Tech stack */}
      <section className="bg-gray-900 py-12">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p className="text-gray-400 text-sm mb-4">Built With</p>
          <div className="flex flex-wrap justify-center gap-3">
            {['IBM Granite', 'IBM watsonx.ai', 'RAG Architecture', 'FastAPI', 'React', 'SQLite', 'TF-IDF Retrieval'].map((t) => (
              <span key={t} className="px-3 py-1.5 bg-gray-800 text-gray-300 rounded-lg text-xs font-medium border border-gray-700">
                {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-6xl mx-auto px-6 py-16 text-center">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          Ready to ace your next interview?
        </h2>
        <p className="text-gray-500 mb-8 text-sm">
          Set up your profile, upload your resume, and start practising in minutes.
        </p>
        <button
          onClick={() => navigate('/profile')}
          className="btn-primary flex items-center gap-2 mx-auto text-base px-8 py-3"
        >
          Get Started <ArrowRight size={18} />
        </button>
      </section>

      <footer className="border-t border-gray-100 py-6 text-center text-xs text-gray-400">
        AI Interview Trainer Agent · Problem Statement No. 22 · IBM Granite / watsonx.ai
      </footer>
    </div>
  )
}
